"""Aggregated environment documentation helpers."""

from __future__ import annotations

from typing import Dict

from gym_gui.core.enums import GameId
from gym_gui.game_docs import BabyAI
from gym_gui.game_docs.ALE import (
    ADVENTURE_HTML,
    AIR_RAID_HTML,
    ASSAULT_HTML,
)
from gym_gui.game_docs.BabyAI import (
    # Complex environments
    BABYAI_ACTION_OBJDOOR_HTML,
    BABYAI_BLOCKED_UNLOCK_PICKUP_HTML,
    BABYAI_BOSSLEVEL_HTML,
    BABYAI_BOSSLEVEL_NOUNLOCK_HTML,
    BABYAI_FINDOBJ_HTML,
    BABYAI_GOTO_DOOR_HTML,
    BABYAI_GOTO_HTML,
    BABYAI_GOTO_IMPUNLOCK_HTML,
    BABYAI_GOTO_LOCAL_HTML,
    BABYAI_GOTO_OBJ_HTML,
    BABYAI_GOTO_OBJDOOR_HTML,
    # GoTo family
    BABYAI_GOTO_REDBALL_GREY_HTML,
    BABYAI_GOTO_REDBALL_HTML,
    BABYAI_GOTO_REDBALL_NODISTS_HTML,
    BABYAI_GOTO_REDBLUEBALL_HTML,
    BABYAI_GOTO_SEQ_HTML,
    BABYAI_KEY_INBOX_HTML,
    BABYAI_KEYCORRIDOR_HTML,
    BABYAI_MINIBOSSLEVEL_HTML,
    BABYAI_MOVETWOACROSS_HTML,
    BABYAI_ONEROOM_HTML,
    BABYAI_OPEN_DOOR_HTML,
    BABYAI_OPEN_DOORSORDER_HTML,
    # Open family
    BABYAI_OPEN_HTML,
    BABYAI_OPEN_REDDOOR_HTML,
    BABYAI_OPEN_TWODOORS_HTML,
    BABYAI_PICKUP_ABOVE_HTML,
    BABYAI_PICKUP_DIST_HTML,
    # Pickup family
    BABYAI_PICKUP_HTML,
    BABYAI_PICKUP_LOC_HTML,
    BABYAI_PUTNEXT_HTML,
    # PutNext family
    BABYAI_PUTNEXT_LOCAL_HTML,
    BABYAI_SYNTH_HTML,
    BABYAI_SYNTHLOC_HTML,
    BABYAI_SYNTHSEQ_HTML,
    BABYAI_UNBLOCK_PICKUP_HTML,
    # Unlock family
    BABYAI_UNLOCK_HTML,
    BABYAI_UNLOCK_LOCAL_HTML,
    BABYAI_UNLOCK_PICKUP_HTML,
    BABYAI_UNLOCK_TO_UNLOCK_HTML,
    get_action_objdoor_html,
    get_blocked_unlock_pickup_html,
    get_bosslevel_html,
    get_bosslevel_nounlock_html,
    get_findobj_html,
    get_goto_door_html,
    get_goto_html,
    get_goto_impunlock_html,
    get_goto_local_html,
    get_goto_obj_html,
    get_goto_objdoor_html,
    get_goto_redball_grey_html,
    get_goto_redball_html,
    get_goto_redball_nodists_html,
    get_goto_redblueball_html,
    get_goto_seq_html,
    get_key_inbox_html,
    get_keycorridor_html,
    get_minibosslevel_html,
    get_movetwoacross_html,
    get_oneroom_html,
    get_open_door_html,
    get_open_doorsorder_html,
    get_open_html,
    get_open_reddoor_html,
    get_open_twodoors_html,
    get_pickup_above_html,
    get_pickup_dist_html,
    get_pickup_html,
    get_pickup_loc_html,
    get_putnext_html,
    get_putnext_local_html,
    get_synth_html,
    get_synthloc_html,
    get_synthseq_html,
    get_unblock_pickup_html,
    get_unlock_html,
    get_unlock_local_html,
    get_unlock_pickup_html,
    get_unlock_to_unlock_html,
)
from gym_gui.game_docs.crafter import (
    CRAFTER_NO_REWARD_HTML,
    CRAFTER_REWARD_HTML,
)
from gym_gui.game_docs.Draughts import (
    AMERICAN_CHECKERS_HTML,
    INTERNATIONAL_DRAUGHTS_HTML,
    RUSSIAN_CHECKERS_HTML,
)
from gym_gui.game_docs.Griddly.multi_agent import (
    GRIDDLY_FORAGERS_HTML,
    GRIDDLY_HEAL_OR_DIE_HTML,
    GRIDDLY_KILL_THE_KING_HTML,
    GRIDDLY_PUSH_MANIA_HTML,
    GRIDDLY_ROBOT_TAG_4V4_HTML,
    GRIDDLY_ROBOT_TAG_8V8_HTML,
    GRIDDLY_ROBOT_TAG_12V12_HTML,
    GRIDDLY_RTS_HTML,
)
from gym_gui.game_docs.Griddly.single_agent import (
    GRIDDLY_BAIT_HTML,
    GRIDDLY_BAIT_WITH_KEYS_HTML,
    GRIDDLY_BUTTERFLIES_AND_SPIDERS_HTML,
    GRIDDLY_CLUSTERS_HTML,
    GRIDDLY_COOK_ME_PASTA_HTML,
    GRIDDLY_DOGGO_HTML,
    GRIDDLY_DRUNK_DWARF_HTML,
    GRIDDLY_EYEBALL_HTML,
    GRIDDLY_LABYRINTH_HTML,
    GRIDDLY_PO_BAIT_HTML,
    GRIDDLY_PO_CLUSTERS_HTML,
    GRIDDLY_PO_COOK_ME_PASTA_HTML,
    GRIDDLY_PO_LABYRINTH_HTML,
    GRIDDLY_PO_SOKOBAN_2_HTML,
    GRIDDLY_PO_ZELDA_HTML,
    GRIDDLY_PO_ZEN_PUZZLE_HTML,
    GRIDDLY_RANDOM_BUTTERFLIES_HTML,
    GRIDDLY_SOKOBAN_2_HTML,
    GRIDDLY_SOKOBAN_HTML,
    GRIDDLY_SPIDER_NEST_HTML,
    GRIDDLY_SPIDERS_HTML,
    GRIDDLY_ZELDA_HTML,
    GRIDDLY_ZELDA_SEQUENTIAL_HTML,
    GRIDDLY_ZEN_PUZZLE_HTML,
)
from gym_gui.game_docs.Gymnasium.Box2D import (
    BIPEDAL_WALKER_HTML,
    CAR_RACING_HTML,
    LUNAR_LANDER_HTML,
)
from gym_gui.game_docs.Gymnasium.MuJuCo import (
    ANT_HTML,
    HALF_CHEETAH_HTML,
    HOPPER_HTML,
    HUMANOID_HTML,
    HUMANOID_STANDUP_HTML,
    INVERTED_DOUBLE_PENDULUM_HTML,
    INVERTED_PENDULUM_HTML,
    PUSHER_HTML,
    REACHER_HTML,
    SWIMMER_HTML,
    WALKER2D_HTML,
)
from gym_gui.game_docs.Gymnasium.ToyText import (
    BLACKJACK_HTML,
    CLIFF_HTML,
    FROZEN_HTML,
    FROZEN_V2_HTML,
    TAXI_HTML,
)
from gym_gui.game_docs.MiniGrid import (
    MINIGRID_BLOCKED_UNLOCK_PICKUP_HTML,
    MINIGRID_CROSSING_HTML,
    MINIGRID_DOORKEY_HTML,
    MINIGRID_DYNAMIC_OBSTACLES_HTML,
    MINIGRID_EMPTY_HTML,
    MINIGRID_LAVAGAP_HTML,
    MINIGRID_MULTIROOM_HTML,
    MINIGRID_OBSTRUCTED_MAZE_HTML,
    MINIGRID_REDBLUEDOORS_HTML,
    get_crossing_html,
    get_doorkey_html,
    get_dynamic_obstacles_html,
    get_empty_html,
    get_lavagap_html,
    get_multiroom_html,
    get_obstructed_maze_html,
    get_redbluedoors_html,
)
from gym_gui.game_docs.Mosaic_MultiGrid import (
    MOSAIC_AMERICAN_FOOTBALL_HTML,
    MOSAIC_BASKETBALL_HTML,
    MOSAIC_COLLECT2VS2_BASE_HTML,
    MOSAIC_COLLECT2VS2_HTML,
    MOSAIC_COLLECT_BASE_HTML,
    MOSAIC_COLLECT_HTML,
    MOSAIC_OVERVIEW_HTML,
    MOSAIC_SOCCER_1VS1_HTML,
    MOSAIC_SOCCER_BASE_HTML,
    MOSAIC_SOCCER_HTML,
    MOSAIC_SOLO_AMERICAN_FOOTBALL_BLUE_HTML,
    MOSAIC_SOLO_AMERICAN_FOOTBALL_GREEN_HTML,
    MOSAIC_SOLO_BASKETBALL_BLUE_HTML,
    MOSAIC_SOLO_BASKETBALL_GREEN_HTML,
    MOSAIC_SOLO_SOCCER_BLUE_HTML,
    MOSAIC_SOLO_SOCCER_GREEN_HTML,
    get_mosaic_multigrid_html,
)

try:  # Optional dependency - MalmoEnv docs (experimental)
    from gym_gui.game_docs.MosaicMalmo import (  # pragma: no cover - experimental
        MALMOENV_ATTIC_HTML,
        MALMOENV_CATCHTHEMOB_HTML,
        MALMOENV_CLIFFWALKING_HTML,
        MALMOENV_DEFAULTFLATWORLD_HTML,
        MALMOENV_DEFAULTWORLD_HTML,
        MALMOENV_EATING_HTML,
        MALMOENV_FINDTHEGOAL_HTML,
        MALMOENV_MAZERUNNER_HTML,
        MALMOENV_MOBCHASE_HTML,
        MALMOENV_OBSTACLES_HTML,
        MALMOENV_TREASUREHUNT_HTML,
        MALMOENV_TRICKYARENA_HTML,
        MALMOENV_VERTICAL_HTML,
    )
    _MOSAIC_MALMO_DOCS_AVAILABLE = True
except Exception:  # pragma: no cover - MalmoEnv optional
    _MOSAIC_MALMO_DOCS_AVAILABLE = False

from gym_gui.game_docs.GRF import (
    # Full match (multi-agent)
    GRF_1V1_EASY_HTML,
    GRF_5V5_HTML,
    GRF_11V11_EASY_HTML,
    GRF_11V11_HARD_HTML,
    GRF_11V11_HTML,
    GRF_ACADEMY_3VS1_WITH_KEEPER_HTML,
    GRF_ACADEMY_CORNER_HTML,
    GRF_ACADEMY_COUNTERATTACK_EASY_HTML,
    GRF_ACADEMY_COUNTERATTACK_HARD_HTML,
    GRF_ACADEMY_EMPTY_GOAL_CLOSE_HTML,
    # Academy (single-agent)
    GRF_ACADEMY_EMPTY_GOAL_HTML,
    GRF_ACADEMY_PASS_AND_SHOOT_HTML,
    GRF_ACADEMY_RUN_PASS_AND_SHOOT_HTML,
    GRF_ACADEMY_RUN_TO_SCORE_HTML,
    GRF_ACADEMY_RUN_TO_SCORE_WITH_KEEPER_HTML,
    GRF_ACADEMY_SINGLE_GOAL_VS_LAZY_HTML,
)
from gym_gui.game_docs.MultiGrid_INI import (
    get_ini_multigrid_html,
)
from gym_gui.game_docs.Olympics import (
    OLYMPICS_WRESTLING_HTML,
)
from gym_gui.game_docs.OpenSpiel import (
    CHECKERS_HTML,
)
from gym_gui.game_docs.PettingZoo import (
    CHESS_HTML,
    CONNECT_FOUR_HTML,
    GO_HTML,
)
from gym_gui.game_docs.Procgen import (
    PROCGEN_BIGFISH_HTML,
    PROCGEN_BOSSFIGHT_HTML,
    PROCGEN_CAVEFLYER_HTML,
    PROCGEN_CHASER_HTML,
    PROCGEN_CLIMBER_HTML,
    PROCGEN_COINRUN_HTML,
    PROCGEN_DODGEBALL_HTML,
    PROCGEN_FRUITBOT_HTML,
    PROCGEN_HEIST_HTML,
    PROCGEN_JUMPER_HTML,
    PROCGEN_LEAPER_HTML,
    PROCGEN_MAZE_HTML,
    PROCGEN_MINER_HTML,
    PROCGEN_NINJA_HTML,
    PROCGEN_PLUNDER_HTML,
    PROCGEN_STARPILOT_HTML,
)
from gym_gui.game_docs.SMAC import (
    SMAC_1C3S5Z_HTML,
    SMAC_2C_VS_64ZG_HTML,
    SMAC_2M_VS_1Z_HTML,
    SMAC_2S3Z_HTML,
    SMAC_2S_VS_1SC_HTML,
    SMAC_3M_HTML,
    SMAC_3S5Z_HTML,
    SMAC_3S5Z_VS_3S6Z_HTML,
    SMAC_3S_VS_3Z_HTML,
    SMAC_3S_VS_4Z_HTML,
    SMAC_3S_VS_5Z_HTML,
    SMAC_5M_VS_6M_HTML,
    SMAC_6H_VS_8Z_HTML,
    SMAC_8M_HTML,
    SMAC_8M_VS_9M_HTML,
    SMAC_10M_VS_11M_HTML,
    SMAC_25M_HTML,
    SMAC_27M_VS_30M_HTML,
    SMAC_BANE_VS_BANE_HTML,
    SMAC_CORRIDOR_HTML,
    SMAC_MMM2_HTML,
    SMAC_MMM_HTML,
    SMAC_SO_MANY_BANELING_HTML,
)
from gym_gui.game_docs.SMACv2 import (
    SMACV2_PROTOSS_5V5_HTML,
    SMACV2_PROTOSS_10V10_HTML,
    SMACV2_PROTOSS_10V11_HTML,
    SMACV2_PROTOSS_20V20_HTML,
    SMACV2_PROTOSS_20V23_HTML,
    SMACV2_PROTOSS_HTML,
    SMACV2_TERRAN_5V5_HTML,
    SMACV2_TERRAN_10V10_HTML,
    SMACV2_TERRAN_10V11_HTML,
    SMACV2_TERRAN_20V20_HTML,
    SMACV2_TERRAN_20V23_HTML,
    SMACV2_TERRAN_HTML,
    SMACV2_ZERG_5V5_HTML,
    SMACV2_ZERG_10V10_HTML,
    SMACV2_ZERG_10V11_HTML,
    SMACV2_ZERG_20V20_HTML,
    SMACV2_ZERG_20V23_HTML,
    SMACV2_ZERG_HTML,
)

try:  # Optional dependency for ViZDoom docs (kept lightweight)
    from gym_gui.game_docs.ViZDoom import (  # pragma: no cover - documentation only
        VIZDOOM_BASIC_HTML,
        VIZDOOM_DEADLY_CORRIDOR_HTML,
        VIZDOOM_DEATHMATCH_HTML,
        VIZDOOM_DEFEND_THE_CENTER_HTML,
        VIZDOOM_DEFEND_THE_LINE_HTML,
        VIZDOOM_HEALTH_GATHERING_HTML,
        VIZDOOM_HEALTH_GATHERING_SUPREME_HTML,
        VIZDOOM_MY_WAY_HOME_HTML,
        VIZDOOM_PREDICT_POSITION_HTML,
        VIZDOOM_TAKE_COVER_HTML,
    )
    _VIZDOOM_DOCS_AVAILABLE = True
except Exception:  # pragma: no cover - ViZDoom optional
    _VIZDOOM_DOCS_AVAILABLE = False

try:  # Optional dependency for NetHack/MiniHack docs
    from gym_gui.game_docs.NetHack import (  # pragma: no cover - documentation only
        MINIHACK_CORRIDOR_HTML,
        # Exploration
        MINIHACK_EXPLORE_MAZE_HTML,
        MINIHACK_HIDENSEEK_HTML,
        MINIHACK_MAZEWALK_HTML,
        MINIHACK_MEMENTO_HTML,
        MINIHACK_RIVER_HTML,
        # Navigation
        MINIHACK_ROOM_HTML,
        MINIHACK_SKILLS_LAVA_HTML,
        MINIHACK_SKILLS_QUEST_HTML,
        # Skills
        MINIHACK_SKILLS_SIMPLE_HTML,
        MINIHACK_SKILLS_WOD_HTML,
        NETHACK_CONTROLS_HTML,
    )
    _NETHACK_DOCS_AVAILABLE = True
except Exception:  # pragma: no cover - NetHack optional
    _NETHACK_DOCS_AVAILABLE = False

_DEFAULT_DOC = (
    "<h3>Documentation unavailable</h3>"
    "<p>This environment does not yet have a descriptive blurb."
    " Check the upstream project for details.</p>"
)

GAME_INFO: Dict[GameId, str] = {
    GameId.TAXI: TAXI_HTML,
    GameId.FROZEN_LAKE: FROZEN_HTML,
    GameId.FROZEN_LAKE_V2: FROZEN_V2_HTML,
    GameId.CLIFF_WALKING: CLIFF_HTML,
    GameId.BLACKJACK: BLACKJACK_HTML,
    GameId.LUNAR_LANDER: LUNAR_LANDER_HTML,
    GameId.CAR_RACING: CAR_RACING_HTML,
    GameId.BIPEDAL_WALKER: BIPEDAL_WALKER_HTML,
    GameId.ANT: ANT_HTML,
    GameId.HALF_CHEETAH: HALF_CHEETAH_HTML,
    GameId.HOPPER: HOPPER_HTML,
    GameId.HUMANOID: HUMANOID_HTML,
    GameId.HUMANOID_STANDUP: HUMANOID_STANDUP_HTML,
    GameId.INVERTED_DOUBLE_PENDULUM: INVERTED_DOUBLE_PENDULUM_HTML,
    GameId.INVERTED_PENDULUM: INVERTED_PENDULUM_HTML,
    GameId.PUSHER: PUSHER_HTML,
    GameId.REACHER: REACHER_HTML,
    GameId.SWIMMER: SWIMMER_HTML,
    GameId.WALKER2D: WALKER2D_HTML,
    GameId.CRAFTER_REWARD: CRAFTER_REWARD_HTML,
    GameId.CRAFTER_NO_REWARD: CRAFTER_NO_REWARD_HTML,
}

_MINIGRID_EMPTY_VARIANTS = (
    GameId.MINIGRID_EMPTY_5x5,
    GameId.MINIGRID_EMPTY_RANDOM_5x5,
    GameId.MINIGRID_EMPTY_6x6,
    GameId.MINIGRID_EMPTY_RANDOM_6x6,
    GameId.MINIGRID_EMPTY_8x8,
    GameId.MINIGRID_EMPTY_16x16,
)
GAME_INFO.update({gid: MINIGRID_EMPTY_HTML for gid in _MINIGRID_EMPTY_VARIANTS})

_MINIGRID_DOORKEY_VARIANTS = (
    GameId.MINIGRID_DOORKEY_5x5,
    GameId.MINIGRID_DOORKEY_6x6,
    GameId.MINIGRID_DOORKEY_8x8,
    GameId.MINIGRID_DOORKEY_16x16,
)
GAME_INFO.update({gid: MINIGRID_DOORKEY_HTML for gid in _MINIGRID_DOORKEY_VARIANTS})

_MINIGRID_LAVAGAP_VARIANTS = (
    GameId.MINIGRID_LAVAGAP_S5,
    GameId.MINIGRID_LAVAGAP_S6,
    GameId.MINIGRID_LAVAGAP_S7,
)
GAME_INFO.update({gid: MINIGRID_LAVAGAP_HTML for gid in _MINIGRID_LAVAGAP_VARIANTS})

_MINIGRID_DYNAMIC_OBSTACLES_VARIANTS = (
    GameId.MINIGRID_DYNAMIC_OBSTACLES_5X5,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_5X5,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_6X6,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_6X6,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_8X8,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_16X16,
)
GAME_INFO.update({gid: MINIGRID_DYNAMIC_OBSTACLES_HTML for gid in _MINIGRID_DYNAMIC_OBSTACLES_VARIANTS})

GAME_INFO[GameId.MINIGRID_BLOCKED_UNLOCK_PICKUP] = MINIGRID_BLOCKED_UNLOCK_PICKUP_HTML

_MINIGRID_MULTIROOM_VARIANTS = (
    GameId.MINIGRID_MULTIROOM_N2_S4,
    GameId.MINIGRID_MULTIROOM_N4_S5,
    GameId.MINIGRID_MULTIROOM_N6,
)
GAME_INFO.update({gid: MINIGRID_MULTIROOM_HTML for gid in _MINIGRID_MULTIROOM_VARIANTS})

GAME_INFO[GameId.MINIGRID_OBSTRUCTED_MAZE_1DLHB] = MINIGRID_OBSTRUCTED_MAZE_HTML
GAME_INFO[GameId.MINIGRID_OBSTRUCTED_MAZE_FULL] = MINIGRID_OBSTRUCTED_MAZE_HTML

# RedBlueDoors variants
_MINIGRID_REDBLUEDOORS_VARIANTS = (
    GameId.MINIGRID_REDBLUE_DOORS_6x6,
    GameId.MINIGRID_REDBLUE_DOORS_8x8,
)
GAME_INFO.update({gid: MINIGRID_REDBLUEDOORS_HTML for gid in _MINIGRID_REDBLUEDOORS_VARIANTS})

# ALE mappings
GAME_INFO[GameId.ADVENTURE_V4] = ADVENTURE_HTML
GAME_INFO[GameId.ALE_ADVENTURE_V5] = ADVENTURE_HTML
GAME_INFO[GameId.AIR_RAID_V4] = AIR_RAID_HTML
GAME_INFO[GameId.ALE_AIR_RAID_V5] = AIR_RAID_HTML
GAME_INFO[GameId.ASSAULT_V4] = ASSAULT_HTML
GAME_INFO[GameId.ALE_ASSAULT_V5] = ASSAULT_HTML

if _VIZDOOM_DOCS_AVAILABLE:
    GAME_INFO.update(
        {
            GameId.VIZDOOM_BASIC: VIZDOOM_BASIC_HTML,
            GameId.VIZDOOM_PREDICT_POSITION: VIZDOOM_PREDICT_POSITION_HTML,
            GameId.VIZDOOM_TAKE_COVER: VIZDOOM_TAKE_COVER_HTML,
            GameId.VIZDOOM_DEFEND_THE_CENTER: VIZDOOM_DEFEND_THE_CENTER_HTML,
            GameId.VIZDOOM_DEFEND_THE_LINE: VIZDOOM_DEFEND_THE_LINE_HTML,
            GameId.VIZDOOM_DEADLY_CORRIDOR: VIZDOOM_DEADLY_CORRIDOR_HTML,
            GameId.VIZDOOM_HEALTH_GATHERING: VIZDOOM_HEALTH_GATHERING_HTML,
            GameId.VIZDOOM_HEALTH_GATHERING_SUPREME: VIZDOOM_HEALTH_GATHERING_SUPREME_HTML,
            GameId.VIZDOOM_MY_WAY_HOME: VIZDOOM_MY_WAY_HOME_HTML,
            GameId.VIZDOOM_DEATHMATCH: VIZDOOM_DEATHMATCH_HTML,
        }
    )

# PettingZoo Classic mappings
GAME_INFO[GameId.CHESS] = CHESS_HTML
GAME_INFO[GameId.CONNECT_FOUR] = CONNECT_FOUR_HTML
GAME_INFO[GameId.GO] = GO_HTML

# OpenSpiel mappings
GAME_INFO[GameId.OPEN_SPIEL_CHECKERS] = CHECKERS_HTML

# Draughts/Checkers variants (custom MOSAIC implementations)
GAME_INFO[GameId.AMERICAN_CHECKERS] = AMERICAN_CHECKERS_HTML
GAME_INFO[GameId.RUSSIAN_CHECKERS] = RUSSIAN_CHECKERS_HTML
GAME_INFO[GameId.INTERNATIONAL_DRAUGHTS] = INTERNATIONAL_DRAUGHTS_HTML

# MOSAIC MultiGrid mappings (v7.0.0 — S/BB/AF/C prefix scheme, TeamObs removed)
# Soccer
GAME_INFO[GameId.MOSAIC_MULTIGRID_S_1V1_INDAGOBS] = MOSAIC_SOCCER_1VS1_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_S_2V2_INDAGOBS] = MOSAIC_SOCCER_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_S_3V3_INDAGOBS] = MOSAIC_SOCCER_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_S_G_1V0] = MOSAIC_SOLO_SOCCER_GREEN_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_S_B_0V1] = MOSAIC_SOLO_SOCCER_BLUE_HTML
# Basketball
GAME_INFO[GameId.MOSAIC_MULTIGRID_BB_1V1_INDAGOBS] = MOSAIC_BASKETBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_BB_2V2_INDAGOBS] = MOSAIC_BASKETBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_BB_3V3_INDAGOBS] = MOSAIC_BASKETBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_BB_G_1V0] = MOSAIC_SOLO_BASKETBALL_GREEN_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_BB_B_0V1] = MOSAIC_SOLO_BASKETBALL_BLUE_HTML
# American Football
GAME_INFO[GameId.MOSAIC_MULTIGRID_AF_1V1_INDAGOBS] = MOSAIC_AMERICAN_FOOTBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_AF_2V2_INDAGOBS] = MOSAIC_AMERICAN_FOOTBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_AF_3V3_INDAGOBS] = MOSAIC_AMERICAN_FOOTBALL_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_AF_G_1V0] = MOSAIC_SOLO_AMERICAN_FOOTBALL_GREEN_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_AF_B_0V1] = MOSAIC_SOLO_AMERICAN_FOOTBALL_BLUE_HTML
# Collect
GAME_INFO[GameId.MOSAIC_MULTIGRID_C_INDAGOBS] = MOSAIC_COLLECT_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_C_1V1_INDAGOBS] = MOSAIC_COLLECT2VS2_HTML
GAME_INFO[GameId.MOSAIC_MULTIGRID_C_2V2_INDAGOBS] = MOSAIC_COLLECT2VS2_HTML
# One-sided cooperative + 4v4 symmetric + asymmetric variants (v7.0.0 full inventory)
# reuse their sport blurb
GAME_INFO.update({
    # Soccer one-sided cooperative
    GameId.MOSAIC_MULTIGRID_S_G_2V0_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_G_3V0_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_G_4V0_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_G_5V0_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_G_6V0_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_B_0V2_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_B_0V3_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_B_0V4_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_B_0V5_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_B_0V6_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_4V4_INDAGOBS: MOSAIC_SOCCER_HTML,
    # Soccer asymmetric competitive (v7.0.0)
    GameId.MOSAIC_MULTIGRID_S_1V2_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_2V1_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_1V3_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_3V1_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_1V4_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_4V1_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_2V3_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_3V2_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_2V4_INDAGOBS: MOSAIC_SOCCER_HTML,
    GameId.MOSAIC_MULTIGRID_S_4V2_INDAGOBS: MOSAIC_SOCCER_HTML,
    # Basketball one-sided cooperative
    GameId.MOSAIC_MULTIGRID_BB_G_2V0_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_G_3V0_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_G_4V0_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_G_5V0_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_G_6V0_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_B_0V2_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_B_0V3_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_B_0V4_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_B_0V5_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_B_0V6_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_4V4_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    # Basketball asymmetric competitive (v7.0.0)
    GameId.MOSAIC_MULTIGRID_BB_1V2_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_2V1_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_1V3_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_3V1_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_1V4_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_4V1_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_2V3_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_3V2_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_2V4_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    GameId.MOSAIC_MULTIGRID_BB_4V2_INDAGOBS: MOSAIC_BASKETBALL_HTML,
    # American Football one-sided cooperative
    GameId.MOSAIC_MULTIGRID_AF_G_2V0_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_G_3V0_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_G_4V0_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_G_5V0_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_G_6V0_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_B_0V2_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_B_0V3_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_B_0V4_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_B_0V5_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_B_0V6_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_4V4_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    # American Football asymmetric competitive (v7.0.0)
    GameId.MOSAIC_MULTIGRID_AF_1V2_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_2V1_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_1V3_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_3V1_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_1V4_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_4V1_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_2V3_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_3V2_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_2V4_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
    GameId.MOSAIC_MULTIGRID_AF_4V2_INDAGOBS: MOSAIC_AMERICAN_FOOTBALL_HTML,
})

# SMAC v1 mappings (hand-designed cooperative micromanagement maps, all 23 maps)
GAME_INFO.update({
    GameId.SMAC_3M: SMAC_3M_HTML,
    GameId.SMAC_8M: SMAC_8M_HTML,
    GameId.SMAC_25M: SMAC_25M_HTML,
    GameId.SMAC_2S3Z: SMAC_2S3Z_HTML,
    GameId.SMAC_3S5Z: SMAC_3S5Z_HTML,
    GameId.SMAC_5M_VS_6M: SMAC_5M_VS_6M_HTML,
    GameId.SMAC_8M_VS_9M: SMAC_8M_VS_9M_HTML,
    GameId.SMAC_10M_VS_11M: SMAC_10M_VS_11M_HTML,
    GameId.SMAC_27M_VS_30M: SMAC_27M_VS_30M_HTML,
    GameId.SMAC_MMM: SMAC_MMM_HTML,
    GameId.SMAC_MMM2: SMAC_MMM2_HTML,
    GameId.SMAC_3S5Z_VS_3S6Z: SMAC_3S5Z_VS_3S6Z_HTML,
    GameId.SMAC_3S_VS_3Z: SMAC_3S_VS_3Z_HTML,
    GameId.SMAC_3S_VS_4Z: SMAC_3S_VS_4Z_HTML,
    GameId.SMAC_3S_VS_5Z: SMAC_3S_VS_5Z_HTML,
    GameId.SMAC_1C3S5Z: SMAC_1C3S5Z_HTML,
    GameId.SMAC_2M_VS_1Z: SMAC_2M_VS_1Z_HTML,
    GameId.SMAC_CORRIDOR: SMAC_CORRIDOR_HTML,
    GameId.SMAC_6H_VS_8Z: SMAC_6H_VS_8Z_HTML,
    GameId.SMAC_2S_VS_1SC: SMAC_2S_VS_1SC_HTML,
    GameId.SMAC_SO_MANY_BANELING: SMAC_SO_MANY_BANELING_HTML,
    GameId.SMAC_BANE_VS_BANE: SMAC_BANE_VS_BANE_HTML,
    GameId.SMAC_2C_VS_64ZG: SMAC_2C_VS_64ZG_HTML,
})

# SMACv2 mappings (procedural unit generation: 3 base maps + 15 scenario presets)
GAME_INFO.update({
    GameId.SMACV2_TERRAN: SMACV2_TERRAN_HTML,
    GameId.SMACV2_PROTOSS: SMACV2_PROTOSS_HTML,
    GameId.SMACV2_ZERG: SMACV2_ZERG_HTML,
    GameId.SMACV2_TERRAN_5V5: SMACV2_TERRAN_5V5_HTML,
    GameId.SMACV2_TERRAN_10V10: SMACV2_TERRAN_10V10_HTML,
    GameId.SMACV2_TERRAN_20V20: SMACV2_TERRAN_20V20_HTML,
    GameId.SMACV2_TERRAN_10V11: SMACV2_TERRAN_10V11_HTML,
    GameId.SMACV2_TERRAN_20V23: SMACV2_TERRAN_20V23_HTML,
    GameId.SMACV2_PROTOSS_5V5: SMACV2_PROTOSS_5V5_HTML,
    GameId.SMACV2_PROTOSS_10V10: SMACV2_PROTOSS_10V10_HTML,
    GameId.SMACV2_PROTOSS_20V20: SMACV2_PROTOSS_20V20_HTML,
    GameId.SMACV2_PROTOSS_10V11: SMACV2_PROTOSS_10V11_HTML,
    GameId.SMACV2_PROTOSS_20V23: SMACV2_PROTOSS_20V23_HTML,
    GameId.SMACV2_ZERG_5V5: SMACV2_ZERG_5V5_HTML,
    GameId.SMACV2_ZERG_10V10: SMACV2_ZERG_10V10_HTML,
    GameId.SMACV2_ZERG_20V20: SMACV2_ZERG_20V20_HTML,
    GameId.SMACV2_ZERG_10V11: SMACV2_ZERG_10V11_HTML,
    GameId.SMACV2_ZERG_20V23: SMACV2_ZERG_20V23_HTML,
})


# GRF Academy mappings (single-agent training drills)
GAME_INFO.update({
    GameId.GRF_ACADEMY_EMPTY_GOAL: GRF_ACADEMY_EMPTY_GOAL_HTML,
    GameId.GRF_ACADEMY_EMPTY_GOAL_CLOSE: GRF_ACADEMY_EMPTY_GOAL_CLOSE_HTML,
    GameId.GRF_ACADEMY_RUN_TO_SCORE: GRF_ACADEMY_RUN_TO_SCORE_HTML,
    GameId.GRF_ACADEMY_RUN_TO_SCORE_WITH_KEEPER: GRF_ACADEMY_RUN_TO_SCORE_WITH_KEEPER_HTML,
    GameId.GRF_ACADEMY_PASS_AND_SHOOT: GRF_ACADEMY_PASS_AND_SHOOT_HTML,
    GameId.GRF_ACADEMY_RUN_PASS_AND_SHOOT: GRF_ACADEMY_RUN_PASS_AND_SHOOT_HTML,
    GameId.GRF_ACADEMY_COUNTERATTACK_EASY: GRF_ACADEMY_COUNTERATTACK_EASY_HTML,
    GameId.GRF_ACADEMY_COUNTERATTACK_HARD: GRF_ACADEMY_COUNTERATTACK_HARD_HTML,
    GameId.GRF_ACADEMY_CORNER: GRF_ACADEMY_CORNER_HTML,
    GameId.GRF_ACADEMY_3V1_WITH_KEEPER: GRF_ACADEMY_3VS1_WITH_KEEPER_HTML,
    GameId.GRF_ACADEMY_SINGLE_GOAL_VS_LAZY: GRF_ACADEMY_SINGLE_GOAL_VS_LAZY_HTML,
})

# GRF Full Match mappings (multi-agent scenarios)
GAME_INFO.update({
    GameId.GRF_1V1_EASY: GRF_1V1_EASY_HTML,
    GameId.GRF_5V5: GRF_5V5_HTML,
    GameId.GRF_11V11_EASY: GRF_11V11_EASY_HTML,
    GameId.GRF_11V11: GRF_11V11_HTML,
    GameId.GRF_11V11_HARD: GRF_11V11_HARD_HTML,
})

# Olympics mappings (competitive physics-based sports)
GAME_INFO[GameId.OLYMPICS_WRESTLING] = OLYMPICS_WRESTLING_HTML

# Griddly mappings (C++ backend grid world platform)
GAME_INFO.update({
    # Single-agent Griddly games
    GameId.GRIDDLY_ZELDA: GRIDDLY_ZELDA_HTML,
    GameId.GRIDDLY_ZELDA_SEQUENTIAL: GRIDDLY_ZELDA_SEQUENTIAL_HTML,
    GameId.GRIDDLY_PO_ZELDA: GRIDDLY_PO_ZELDA_HTML,
    GameId.GRIDDLY_SOKOBAN: GRIDDLY_SOKOBAN_HTML,
    GameId.GRIDDLY_SOKOBAN_2: GRIDDLY_SOKOBAN_2_HTML,
    GameId.GRIDDLY_PO_SOKOBAN_2: GRIDDLY_PO_SOKOBAN_2_HTML,
    GameId.GRIDDLY_CLUSTERS: GRIDDLY_CLUSTERS_HTML,
    GameId.GRIDDLY_PO_CLUSTERS: GRIDDLY_PO_CLUSTERS_HTML,
    GameId.GRIDDLY_BAIT: GRIDDLY_BAIT_HTML,
    GameId.GRIDDLY_BAIT_WITH_KEYS: GRIDDLY_BAIT_WITH_KEYS_HTML,
    GameId.GRIDDLY_PO_BAIT: GRIDDLY_PO_BAIT_HTML,
    GameId.GRIDDLY_ZEN_PUZZLE: GRIDDLY_ZEN_PUZZLE_HTML,
    GameId.GRIDDLY_PO_ZEN_PUZZLE: GRIDDLY_PO_ZEN_PUZZLE_HTML,
    GameId.GRIDDLY_LABYRINTH: GRIDDLY_LABYRINTH_HTML,
    GameId.GRIDDLY_PO_LABYRINTH: GRIDDLY_PO_LABYRINTH_HTML,
    GameId.GRIDDLY_COOK_ME_PASTA: GRIDDLY_COOK_ME_PASTA_HTML,
    GameId.GRIDDLY_PO_COOK_ME_PASTA: GRIDDLY_PO_COOK_ME_PASTA_HTML,
    GameId.GRIDDLY_SPIDERS: GRIDDLY_SPIDERS_HTML,
    GameId.GRIDDLY_SPIDER_NEST: GRIDDLY_SPIDER_NEST_HTML,
    GameId.GRIDDLY_BUTTERFLIES_AND_SPIDERS: GRIDDLY_BUTTERFLIES_AND_SPIDERS_HTML,
    GameId.GRIDDLY_RANDOM_BUTTERFLIES: GRIDDLY_RANDOM_BUTTERFLIES_HTML,
    GameId.GRIDDLY_EYEBALL: GRIDDLY_EYEBALL_HTML,
    GameId.GRIDDLY_DRUNK_DWARF: GRIDDLY_DRUNK_DWARF_HTML,
    GameId.GRIDDLY_DOGGO: GRIDDLY_DOGGO_HTML,
    # Multi-agent Griddly games
    GameId.GRIDDLY_RTS: GRIDDLY_RTS_HTML,
    GameId.GRIDDLY_PUSH_MANIA: GRIDDLY_PUSH_MANIA_HTML,
    GameId.GRIDDLY_KILL_THE_KING: GRIDDLY_KILL_THE_KING_HTML,
    GameId.GRIDDLY_HEAL_OR_DIE: GRIDDLY_HEAL_OR_DIE_HTML,
    GameId.GRIDDLY_ROBOT_TAG_4V4: GRIDDLY_ROBOT_TAG_4V4_HTML,
    GameId.GRIDDLY_ROBOT_TAG_8V8: GRIDDLY_ROBOT_TAG_8V8_HTML,
    GameId.GRIDDLY_ROBOT_TAG_12V12: GRIDDLY_ROBOT_TAG_12V12_HTML,
    GameId.GRIDDLY_FORAGERS: GRIDDLY_FORAGERS_HTML,
})

# RWARE (Robotic Warehouse) mappings
try:
    from gym_gui.game_docs.RWARE import (
        RWARE_LARGE_4AG_HARD_HTML,
        RWARE_LARGE_4AG_HTML,
        RWARE_LARGE_8AG_HARD_HTML,
        RWARE_LARGE_8AG_HTML,
        RWARE_MEDIUM_2AG_HTML,
        RWARE_MEDIUM_4AG_EASY_HTML,
        RWARE_MEDIUM_4AG_HARD_HTML,
        RWARE_MEDIUM_4AG_HTML,
        RWARE_SMALL_2AG_HTML,
        RWARE_SMALL_4AG_HTML,
        RWARE_TINY_2AG_HTML,
        RWARE_TINY_4AG_HTML,
    )

    GAME_INFO.update({
        GameId.RWARE_TINY_2AG: RWARE_TINY_2AG_HTML,
        GameId.RWARE_TINY_4AG: RWARE_TINY_4AG_HTML,
        GameId.RWARE_SMALL_2AG: RWARE_SMALL_2AG_HTML,
        GameId.RWARE_SMALL_4AG: RWARE_SMALL_4AG_HTML,
        GameId.RWARE_MEDIUM_2AG: RWARE_MEDIUM_2AG_HTML,
        GameId.RWARE_MEDIUM_4AG: RWARE_MEDIUM_4AG_HTML,
        GameId.RWARE_MEDIUM_4AG_EASY: RWARE_MEDIUM_4AG_EASY_HTML,
        GameId.RWARE_MEDIUM_4AG_HARD: RWARE_MEDIUM_4AG_HARD_HTML,
        GameId.RWARE_LARGE_4AG: RWARE_LARGE_4AG_HTML,
        GameId.RWARE_LARGE_4AG_HARD: RWARE_LARGE_4AG_HARD_HTML,
        GameId.RWARE_LARGE_8AG: RWARE_LARGE_8AG_HTML,
        GameId.RWARE_LARGE_8AG_HARD: RWARE_LARGE_8AG_HARD_HTML,
    })
except ImportError:
    pass  # rware docs not available

# Procgen mappings
GAME_INFO.update({
    GameId.PROCGEN_BIGFISH: PROCGEN_BIGFISH_HTML,
    GameId.PROCGEN_BOSSFIGHT: PROCGEN_BOSSFIGHT_HTML,
    GameId.PROCGEN_CAVEFLYER: PROCGEN_CAVEFLYER_HTML,
    GameId.PROCGEN_CHASER: PROCGEN_CHASER_HTML,
    GameId.PROCGEN_CLIMBER: PROCGEN_CLIMBER_HTML,
    GameId.PROCGEN_COINRUN: PROCGEN_COINRUN_HTML,
    GameId.PROCGEN_DODGEBALL: PROCGEN_DODGEBALL_HTML,
    GameId.PROCGEN_FRUITBOT: PROCGEN_FRUITBOT_HTML,
    GameId.PROCGEN_HEIST: PROCGEN_HEIST_HTML,
    GameId.PROCGEN_JUMPER: PROCGEN_JUMPER_HTML,
    GameId.PROCGEN_LEAPER: PROCGEN_LEAPER_HTML,
    GameId.PROCGEN_MAZE: PROCGEN_MAZE_HTML,
    GameId.PROCGEN_MINER: PROCGEN_MINER_HTML,
    GameId.PROCGEN_NINJA: PROCGEN_NINJA_HTML,
    GameId.PROCGEN_PLUNDER: PROCGEN_PLUNDER_HTML,
    GameId.PROCGEN_STARPILOT: PROCGEN_STARPILOT_HTML,
})

# BabyAI mappings (language-grounded instruction following)
GAME_INFO.update({
    # GoTo family
    GameId.BABYAI_GOTO_REDBALL_GREY: BABYAI_GOTO_REDBALL_GREY_HTML,
    GameId.BABYAI_GOTO_REDBALL: BABYAI_GOTO_REDBALL_HTML,
    GameId.BABYAI_GOTO_REDBALL_NODISTS: BABYAI_GOTO_REDBALL_NODISTS_HTML,
    GameId.BABYAI_GOTO_OBJ: BABYAI_GOTO_OBJ_HTML,
    GameId.BABYAI_GOTO_LOCAL: BABYAI_GOTO_LOCAL_HTML,
    GameId.BABYAI_GOTO: BABYAI_GOTO_HTML,
    GameId.BABYAI_GOTO_IMPUNLOCK: BABYAI_GOTO_IMPUNLOCK_HTML,
    GameId.BABYAI_GOTO_SEQ: BABYAI_GOTO_SEQ_HTML,
    GameId.BABYAI_GOTO_REDBLUEBALL: BABYAI_GOTO_REDBLUEBALL_HTML,
    GameId.BABYAI_GOTO_DOOR: BABYAI_GOTO_DOOR_HTML,
    GameId.BABYAI_GOTO_OBJDOOR: BABYAI_GOTO_OBJDOOR_HTML,
    # Open family
    GameId.BABYAI_OPEN: BABYAI_OPEN_HTML,
    GameId.BABYAI_OPEN_REDDOOR: BABYAI_OPEN_REDDOOR_HTML,
    GameId.BABYAI_OPEN_DOOR: BABYAI_OPEN_DOOR_HTML,
    GameId.BABYAI_OPEN_TWODOORS: BABYAI_OPEN_TWODOORS_HTML,
    GameId.BABYAI_OPEN_DOORSORDER_N2: BABYAI_OPEN_DOORSORDER_HTML,
    GameId.BABYAI_OPEN_DOORSORDER_N4: BABYAI_OPEN_DOORSORDER_HTML,
    # Pickup family
    GameId.BABYAI_PICKUP: BABYAI_PICKUP_HTML,
    GameId.BABYAI_UNBLOCK_PICKUP: BABYAI_UNBLOCK_PICKUP_HTML,
    GameId.BABYAI_PICKUP_LOC: BABYAI_PICKUP_LOC_HTML,
    GameId.BABYAI_PICKUP_DIST: BABYAI_PICKUP_DIST_HTML,
    GameId.BABYAI_PICKUP_ABOVE: BABYAI_PICKUP_ABOVE_HTML,
    # Unlock family
    GameId.BABYAI_UNLOCK: BABYAI_UNLOCK_HTML,
    GameId.BABYAI_UNLOCK_LOCAL: BABYAI_UNLOCK_LOCAL_HTML,
    GameId.BABYAI_KEY_INBOX: BABYAI_KEY_INBOX_HTML,
    GameId.BABYAI_UNLOCK_PICKUP: BABYAI_UNLOCK_PICKUP_HTML,
    GameId.BABYAI_BLOCKED_UNLOCK_PICKUP: BABYAI_BLOCKED_UNLOCK_PICKUP_HTML,
    GameId.BABYAI_UNLOCK_TO_UNLOCK: BABYAI_UNLOCK_TO_UNLOCK_HTML,
    # PutNext family
    GameId.BABYAI_PUTNEXT_LOCAL: BABYAI_PUTNEXT_LOCAL_HTML,
    GameId.BABYAI_PUTNEXT: BABYAI_PUTNEXT_HTML,
    # Complex environments
    GameId.BABYAI_ACTION_OBJDOOR: BABYAI_ACTION_OBJDOOR_HTML,
    GameId.BABYAI_FINDOBJ_S5: BABYAI_FINDOBJ_HTML,
    GameId.BABYAI_KEYCORRIDOR_S3R1: BABYAI_KEYCORRIDOR_HTML,
    GameId.BABYAI_KEYCORRIDOR_S3R2: BABYAI_KEYCORRIDOR_HTML,
    GameId.BABYAI_KEYCORRIDOR_S3R3: BABYAI_KEYCORRIDOR_HTML,
    GameId.BABYAI_ONEROOM_S8: BABYAI_ONEROOM_HTML,
    GameId.BABYAI_MOVETWOACROSS_S8N9: BABYAI_MOVETWOACROSS_HTML,
    GameId.BABYAI_SYNTH: BABYAI_SYNTH_HTML,
    GameId.BABYAI_SYNTHLOC: BABYAI_SYNTHLOC_HTML,
    GameId.BABYAI_SYNTHSEQ: BABYAI_SYNTHSEQ_HTML,
    GameId.BABYAI_MINIBOSSLEVEL: BABYAI_MINIBOSSLEVEL_HTML,
    GameId.BABYAI_BOSSLEVEL: BABYAI_BOSSLEVEL_HTML,
    GameId.BABYAI_BOSSLEVEL_NOUNLOCK: BABYAI_BOSSLEVEL_NOUNLOCK_HTML,
})

# Jumanji mappings (JAX-based environments)
try:
    from gym_gui.game_docs.Jumanji import (
        # Phase 2: Packing
        BINPACK_HTML,
        # Phase 3: Routing
        CLEANER_HTML,
        CONNECTOR_HTML,
        CVRP_HTML,
        FLATPACK_HTML,
        # Phase 1: Logic
        GAME2048_HTML,
        GRAPH_COLORING_HTML,
        JOBSHOP_HTML,
        KNAPSACK_HTML,
        MAZE_HTML,
        MINESWEEPER_HTML,
        MMST_HTML,
        MULTI_CVRP_HTML,
        PACMAN_HTML,
        ROBOT_WAREHOUSE_HTML,
        RUBIKS_CUBE_HTML,
        SLIDING_PUZZLE_HTML,
        SNAKE_HTML,
        SOKOBAN_HTML,
        SUDOKU_HTML,
        TETRIS_HTML,
        TSP_HTML,
    )
    GAME_INFO.update({
        # Phase 1: Logic
        GameId.JUMANJI_GAME2048: GAME2048_HTML,
        GameId.JUMANJI_MINESWEEPER: MINESWEEPER_HTML,
        GameId.JUMANJI_RUBIKS_CUBE: RUBIKS_CUBE_HTML,
        GameId.JUMANJI_SLIDING_PUZZLE: SLIDING_PUZZLE_HTML,
        GameId.JUMANJI_SUDOKU: SUDOKU_HTML,
        GameId.JUMANJI_GRAPH_COLORING: GRAPH_COLORING_HTML,
        # Phase 2: Packing
        GameId.JUMANJI_BINPACK: BINPACK_HTML,
        GameId.JUMANJI_FLATPACK: FLATPACK_HTML,
        GameId.JUMANJI_JOBSHOP: JOBSHOP_HTML,
        GameId.JUMANJI_KNAPSACK: KNAPSACK_HTML,
        GameId.JUMANJI_TETRIS: TETRIS_HTML,
        # Phase 3: Routing
        GameId.JUMANJI_CLEANER: CLEANER_HTML,
        GameId.JUMANJI_CONNECTOR: CONNECTOR_HTML,
        GameId.JUMANJI_CVRP: CVRP_HTML,
        GameId.JUMANJI_MAZE: MAZE_HTML,
        GameId.JUMANJI_MMST: MMST_HTML,
        GameId.JUMANJI_MULTI_CVRP: MULTI_CVRP_HTML,
        GameId.JUMANJI_PACMAN: PACMAN_HTML,
        GameId.JUMANJI_ROBOT_WAREHOUSE: ROBOT_WAREHOUSE_HTML,
        GameId.JUMANJI_SNAKE: SNAKE_HTML,
        GameId.JUMANJI_SOKOBAN: SOKOBAN_HTML,
        GameId.JUMANJI_TSP: TSP_HTML,
    })
except ImportError:
    pass  # Jumanji docs optional

if _MOSAIC_MALMO_DOCS_AVAILABLE:  # pragma: no cover - experimental
    GAME_INFO.update({
        # MalmoEnv (MOSAIC MalmoEnv single-agent Minecraft missions)
        GameId.MALMOENV_ATTIC: MALMOENV_ATTIC_HTML,
        GameId.MALMOENV_CATCHTHEMOB: MALMOENV_CATCHTHEMOB_HTML,
        GameId.MALMOENV_CLIFFWALKING: MALMOENV_CLIFFWALKING_HTML,
        GameId.MALMOENV_DEFAULTFLATWORLD: MALMOENV_DEFAULTFLATWORLD_HTML,
        GameId.MALMOENV_DEFAULTWORLD: MALMOENV_DEFAULTWORLD_HTML,
        GameId.MALMOENV_EATING: MALMOENV_EATING_HTML,
        GameId.MALMOENV_FINDTHEGOAL: MALMOENV_FINDTHEGOAL_HTML,
        GameId.MALMOENV_MAZERUNNER: MALMOENV_MAZERUNNER_HTML,
        GameId.MALMOENV_MOBCHASE: MALMOENV_MOBCHASE_HTML,
        GameId.MALMOENV_OBSTACLES: MALMOENV_OBSTACLES_HTML,
        GameId.MALMOENV_TRICKYARENA: MALMOENV_TRICKYARENA_HTML,
        GameId.MALMOENV_TREASUREHUNT: MALMOENV_TREASUREHUNT_HTML,
        GameId.MALMOENV_VERTICAL: MALMOENV_VERTICAL_HTML,
    })


from gym_gui.game_docs.mosaic_welcome import MULTI_KEYBOARD_HTML


def _socialjax_controls_html(env_name: str) -> str:
    """Build a Controls section HTML table for a SocialJax environment.

    Uses SOCIALJAX_ACTIONS_BY_ENV for action names and a per-env key map
    so the table always matches the actual keyboard bindings.
    """
    from gym_gui.core.adapters.socialjax import SOCIALJAX_ACTIONS_BY_ENV

    # Key display for each action index per env.
    # lb_foraging has no turning; coop_mining uses egocentric movement.
    # All other envs share the same base 7-key layout.
    _KEY_MAP: dict[str, dict[int, str]] = {
        "lb_foraging": {
            0: "Space",
            1: "W or Up",
            2: "S or Down",
            3: "A or Left",
            4: "D or Right",
            5: "F or Enter",
        },
        "coop_mining": {
            0: "Q",
            1: "E",
            2: "A or Left (strafe left)",
            3: "D or Right (strafe right)",
            4: "W or Up (forward)",
            5: "S or Down (backward)",
            6: "Space",
            7: "F",
        },
    }
    _BASE_7: dict[int, str] = {
        0: "Q",
        1: "E",
        2: "A or Left",
        3: "D or Right",
        4: "W or Up",
        5: "S or Down",
        6: "Space",
        7: "F",
        8: "Z",
    }

    actions = SOCIALJAX_ACTIONS_BY_ENV.get(env_name, ())
    if not actions:
        return ""

    key_map = _KEY_MAP.get(env_name, _BASE_7)

    rows = ""
    for idx, label in enumerate(actions):
        key = key_map.get(idx, "")
        rows += (
            f'<tr><td style="border:1px solid #ddd;padding:5px;text-align:center;">'
            f'<code>{idx}</code></td>'
            f'<td style="border:1px solid #ddd;padding:5px;">{label}</td>'
            f'<td style="border:1px solid #ddd;padding:5px;font-family:monospace;">{key}</td></tr>\n'
        )

    return (
        "\n<h3>Actions &amp; Keyboard Controls</h3>\n"
        '<table style="border-collapse:collapse;width:100%;margin-top:8px;">\n'
        '<tr style="background-color:#f2f2f2;">'
        '<th style="border:1px solid #ddd;padding:5px;">Index</th>'
        '<th style="border:1px solid #ddd;padding:5px;">Action</th>'
        '<th style="border:1px solid #ddd;padding:5px;">Key</th></tr>\n'
        + rows
        + "</table>\n"
    )


def _get_socialjax_doc(env_id: str) -> str:
    """Return HTML documentation for a SocialJax environment.

    Extracts the env name from env_id (e.g. ``"socialjax/coop_mining"`` -> ``"coop_mining"``)
    and maps it to the corresponding documentation module.
    """
    from gym_gui.game_docs.SocialJax import (
        SOCIALJAX_CLEAN_UP_HTML,
        SOCIALJAX_COIN_GAME_HTML,
        SOCIALJAX_COOP_MINING_HTML,
        SOCIALJAX_GIFT_HTML,
        SOCIALJAX_HARVEST_COMMON_OPEN_HTML,
        SOCIALJAX_LB_FORAGING_HTML,
        SOCIALJAX_MUSHROOMS_HTML,
        SOCIALJAX_PD_ARENA_HTML,
        SOCIALJAX_TERRITORY_OPEN_HTML,
    )

    _DOC_MAP = {
        "coin_game": SOCIALJAX_COIN_GAME_HTML,
        "harvest_common_open": SOCIALJAX_HARVEST_COMMON_OPEN_HTML,
        "clean_up": SOCIALJAX_CLEAN_UP_HTML,
        "coop_mining": SOCIALJAX_COOP_MINING_HTML,
        "territory_open": SOCIALJAX_TERRITORY_OPEN_HTML,
        "pd_arena": SOCIALJAX_PD_ARENA_HTML,
        "mushrooms": SOCIALJAX_MUSHROOMS_HTML,
        "gift": SOCIALJAX_GIFT_HTML,
        "lb_foraging": SOCIALJAX_LB_FORAGING_HTML,
    }

    env_name = env_id.replace("socialjax/", "")
    base_html = _DOC_MAP.get(env_name, f"<p>SocialJax environment: <code>{env_name}</code></p>")
    controls = _socialjax_controls_html(env_name)
    return base_html + controls


def _get_meltingpot_doc(env_id: str) -> str:
    """Return HTML documentation for a MeltingPot substrate.

    Extracts the base substrate name from env_id (e.g.
    ``"meltingpot/collaborative_cooking__ring"`` -> ``"collaborative_cooking"``)
    and maps it to the corresponding documentation module.
    """
    from gym_gui.game_docs.MeltingPot import (
        MELTINGPOT_ALLELOPATHIC_HARVEST_HTML,
        MELTINGPOT_CLEAN_UP_HTML,
        MELTINGPOT_COLLABORATIVE_COOKING_HTML,
        MELTINGPOT_COMMONS_HARVEST_HTML,
        MELTINGPOT_KING_OF_THE_HILL_HTML,
        MELTINGPOT_PRISONERS_DILEMMA_HTML,
        MELTINGPOT_STAG_HUNT_HTML,
        MELTINGPOT_TERRITORY_HTML,
    )

    _DOC_MAP = {
        "allelopathic_harvest": MELTINGPOT_ALLELOPATHIC_HARVEST_HTML,
        "clean_up": MELTINGPOT_CLEAN_UP_HTML,
        "collaborative_cooking": MELTINGPOT_COLLABORATIVE_COOKING_HTML,
        "commons_harvest": MELTINGPOT_COMMONS_HARVEST_HTML,
        "paintball": MELTINGPOT_KING_OF_THE_HILL_HTML,
        "prisoners_dilemma_in_the_matrix": MELTINGPOT_PRISONERS_DILEMMA_HTML,
        "stag_hunt_in_the_matrix": MELTINGPOT_STAG_HUNT_HTML,
        "territory": MELTINGPOT_TERRITORY_HTML,
    }

    # "meltingpot/collaborative_cooking__ring" -> "collaborative_cooking"
    substrate = env_id.split("/", 1)[-1]
    base = substrate.split("__")[0]

    return _DOC_MAP.get(base, _DEFAULT_DOC)


def _get_overcooked_doc(env_id: str) -> str:
    """Return HTML documentation for an Overcooked layout."""
    from gym_gui.game_docs.Overcooked import (
        OVERCOOKED_ASYMMETRIC_ADVANTAGES_HTML,
        OVERCOOKED_COORDINATION_RING_HTML,
        OVERCOOKED_COUNTER_CIRCUIT_HTML,
        OVERCOOKED_CRAMPED_ROOM_HTML,
        OVERCOOKED_FORCED_COORDINATION_HTML,
    )

    _DOC_MAP = {
        "cramped_room": OVERCOOKED_CRAMPED_ROOM_HTML,
        "asymmetric_advantages": OVERCOOKED_ASYMMETRIC_ADVANTAGES_HTML,
        "coordination_ring": OVERCOOKED_COORDINATION_RING_HTML,
        "forced_coordination": OVERCOOKED_FORCED_COORDINATION_HTML,
        "counter_circuit": OVERCOOKED_COUNTER_CIRCUIT_HTML,
    }

    # "overcooked/cramped_room" -> "cramped_room"
    layout = env_id.split("/", 1)[-1]

    return _DOC_MAP.get(layout, _DEFAULT_DOC)


def _get_hemac_doc(env_id: str) -> str:
    """Return HTML documentation for a HeMAC scenario."""
    from gym_gui.game_docs.hemac import (
        get_complex_fleet_html,
        get_fleet_html,
        get_simple_fleet_html,
    )

    if "simple-fleet" in env_id:
        return get_simple_fleet_html(env_id)
    if "complex-fleet" in env_id:
        return get_complex_fleet_html(env_id)
    return get_fleet_html(env_id)


def get_game_info(game_id: GameId) -> str:
    """Return HTML documentation for the specified environment."""

    # Handle Empty variants dynamically
    if game_id in (GameId.MINIGRID_EMPTY_5x5, GameId.MINIGRID_EMPTY_RANDOM_5x5,
                   GameId.MINIGRID_EMPTY_6x6, GameId.MINIGRID_EMPTY_RANDOM_6x6,
                   GameId.MINIGRID_EMPTY_8x8, GameId.MINIGRID_EMPTY_16x16):
        return get_empty_html(game_id.value)

    # Handle DoorKey variants dynamically
    if game_id in (GameId.MINIGRID_DOORKEY_5x5, GameId.MINIGRID_DOORKEY_6x6,
                   GameId.MINIGRID_DOORKEY_8x8, GameId.MINIGRID_DOORKEY_16x16):
        return get_doorkey_html(game_id.value)

    # Handle LavaGap variants dynamically
    if game_id in (GameId.MINIGRID_LAVAGAP_S5, GameId.MINIGRID_LAVAGAP_S6,
                   GameId.MINIGRID_LAVAGAP_S7):
        return get_lavagap_html(game_id.value)

    # Handle Dynamic Obstacles variants dynamically
    if game_id in (GameId.MINIGRID_DYNAMIC_OBSTACLES_5X5, GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_5X5,
                   GameId.MINIGRID_DYNAMIC_OBSTACLES_6X6, GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_6X6,
                   GameId.MINIGRID_DYNAMIC_OBSTACLES_8X8, GameId.MINIGRID_DYNAMIC_OBSTACLES_16X16):
        return get_dynamic_obstacles_html(game_id.value)

    # Handle MultiRoom variants dynamically
    if game_id in (GameId.MINIGRID_MULTIROOM_N2_S4, GameId.MINIGRID_MULTIROOM_N4_S5,
                   GameId.MINIGRID_MULTIROOM_N6):
        return get_multiroom_html(game_id.value)

    # Handle Obstructed Maze variants dynamically
    if game_id in (GameId.MINIGRID_OBSTRUCTED_MAZE_1DLHB, GameId.MINIGRID_OBSTRUCTED_MAZE_FULL):
        return get_obstructed_maze_html(game_id.value)

    # Handle Crossing variants dynamically
    if game_id in (GameId.MINIGRID_LAVA_CROSSING_S9N1, GameId.MINIGRID_LAVA_CROSSING_S9N2,
                   GameId.MINIGRID_LAVA_CROSSING_S9N3, GameId.MINIGRID_LAVA_CROSSING_S11N5,
                   GameId.MINIGRID_SIMPLE_CROSSING_S9N1, GameId.MINIGRID_SIMPLE_CROSSING_S9N2,
                   GameId.MINIGRID_SIMPLE_CROSSING_S9N3, GameId.MINIGRID_SIMPLE_CROSSING_S11N5):
        return get_crossing_html(game_id.value)

    # Handle RedBlueDoors variants dynamically
    if game_id in (GameId.MINIGRID_REDBLUE_DOORS_6x6, GameId.MINIGRID_REDBLUE_DOORS_8x8):
        return get_redbluedoors_html(game_id.value)

    # Handle INI MultiGrid variants dynamically
    _ini_multigrid_variants = (
        GameId.INI_MULTIGRID_EMPTY_5X5,
        GameId.INI_MULTIGRID_EMPTY_RANDOM_5X5,
        GameId.INI_MULTIGRID_EMPTY_6X6,
        GameId.INI_MULTIGRID_EMPTY_RANDOM_6X6,
        GameId.INI_MULTIGRID_EMPTY_8X8,
        GameId.INI_MULTIGRID_EMPTY_16X16,
        GameId.INI_MULTIGRID_RED_BLUE_DOORS_6X6,
        GameId.INI_MULTIGRID_RED_BLUE_DOORS_8X8,
        GameId.INI_MULTIGRID_LOCKED_HALLWAY_2ROOMS,
        GameId.INI_MULTIGRID_LOCKED_HALLWAY_4ROOMS,
        GameId.INI_MULTIGRID_LOCKED_HALLWAY_6ROOMS,
        GameId.INI_MULTIGRID_BLOCKED_UNLOCK_PICKUP,
        GameId.INI_MULTIGRID_PLAYGROUND,
    )
    if game_id in _ini_multigrid_variants:
        ini_doc = get_ini_multigrid_html(game_id.value)
        return ini_doc + "\n\n" + MULTI_KEYBOARD_HTML

    # Handle MOSAIC MultiGrid variants via family check (v6.8.0+)
    from gym_gui.core.enums import ENVIRONMENT_FAMILY_BY_GAME, EnvironmentFamily
    family = ENVIRONMENT_FAMILY_BY_GAME.get(game_id)
    if family == EnvironmentFamily.MOSAIC_MULTIGRID:
        mosaic_doc = get_mosaic_multigrid_html(game_id.value)
        return mosaic_doc + "\n\n" + MULTI_KEYBOARD_HTML
    if family == EnvironmentFamily.MALMOENV:
        return GAME_INFO.get(game_id, _DEFAULT_DOC)

    if family == EnvironmentFamily.SOCIALJAX:
        return _get_socialjax_doc(game_id.value)

    if family == EnvironmentFamily.MELTINGPOT:
        doc = _get_meltingpot_doc(game_id.value)
        return doc + "\n\n" + MULTI_KEYBOARD_HTML

    # Handle Overcooked variants by layout name
    if family == EnvironmentFamily.OVERCOOKED:
        doc = _get_overcooked_doc(game_id.value)
        return doc + "\n\n" + MULTI_KEYBOARD_HTML

    if family == EnvironmentFamily.HEMAC:
        doc = _get_hemac_doc(game_id.value)
        return doc + "\n\n" + MULTI_KEYBOARD_HTML

    # Get base documentation from flat dict
    base_doc = GAME_INFO.get(game_id, _DEFAULT_DOC)
    return base_doc


__all__ = ["GAME_INFO", "get_game_info"]
