"""Documentation for Gymnasium ToyText environments."""
from __future__ import annotations

TAXI_HTML = (
    "<h3>Taxi-v4</h3>"
    "<p>Pickup and drop off passengers on a small grid with walls.</p>"
    "<h4>Starting state</h4>"
    "<p>The initial state is sampled uniformly from positions where the passenger is not in the taxi and not at their destination. There are 300 possible initial states.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>-1 per step (time penalty)</li>"
    "<li>+20 for successfully delivering the passenger</li>"
    "<li>-10 for illegal pickup or drop-off</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: passenger successfully dropped off</li>"
    "<li>Truncation (with time_limit): episode length 200</li>"
    "</ul>"
    "<h4>Info returned</h4>"
    "<p><code>step()</code> and <code>reset()</code> return an <code>info</code> dict that may include:</p>"
    "<ul>"
    "<li><code>p</code> — transition probability</li>"
    "<li><code>action_mask</code> — boolean mask indicating which actions will change state</li>"
    "</ul>"
    "<h4>Keyboard (human controls)</h4>"
    "<p>Map the taxi action space to keys for human play:</p>"
    "<ul>"
    "<li>South (0) → Down arrow</li>"
    "<li>East (1) → Right arrow</li>"
    "<li>North (2) → Up arrow</li>"
    "<li>West (3) → Left arrow</li>"
    "<li>Pickup → Spacebar</li>"
    "<li>Dropoff → E</li>"
    "</ul>"
    "<h4>Arguments / Config</h4>"
    "<p><strong>Note:</strong> The current Gymnasium Taxi-v4 environment uses deterministic movement and does not support stochastic variants.</p>"
    "<p><code>is_raining</code> and <code>fickle_passenger</code> parameters shown in the UI are for reference only and have no effect in the current implementation.</p>"
    "<p>See the docs: <a href=\"https://gymnasium.farama.org/environments/toy_text/taxi/\">Taxi (Gymnasium)</a></p>"
)


FROZEN_HTML = (
    "<h3>FrozenLake-v1</h3>"
    "<p>A grid world where the agent must reach the goal while avoiding holes.</p>"
    "<h4>Starting state</h4>"
    "<p>The episode starts at the upper-left corner (state 0).</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Reach goal → +1</li>"
    "<li>Reach hole → 0</li>"
    "<li>Each frozen tile otherwise → 0</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: fall into a hole, or reach the goal</li>"
    "<li>Truncation (with time_limit): 100 steps for 4x4, 200 for 8x8</li>"
    "</ul>"
    "<h4>Keyboard (human controls)</h4>"
    "<ul>"
    "<li>Up → Up arrow</li>"
    "<li>Right → Right arrow</li>"
    "<li>Down → Down arrow</li>"
    "<li>Left → Left arrow</li>"
    "</ul>"
    "<h4>Arguments / Config</h4>"
    "<p><code>is_slippery</code>: when True, movement is stochastic (slips to perpendicular directions); when False movement is deterministic.</p>"
    "<p>See the docs: <a href=\"https://gymnasium.farama.org/environments/toy_text/frozen_lake/\">FrozenLake (Gymnasium)</a></p>"
)


FROZEN_V2_HTML = (
    "<h3>FrozenLake-v2</h3>"
    "<p>A highly configurable grid world where the agent must reach the goal while avoiding holes.</p>"
    "<h4>Starting state</h4>"
    "<p>The episode starts at a configurable position (default: upper-left corner at position (0,0)).</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Reach goal → +1</li>"
    "<li>Reach hole → 0</li>"
    "<li>Each frozen tile otherwise → 0</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: fall into a hole, or reach the goal</li>"
    "<li>Truncation (with time_limit): 100 steps for 4×4, 200 for 8×8, scales with grid size</li>"
    "</ul>"
    "<h4>Keyboard (human controls)</h4>"
    "<ul>"
    "<li>Up → Up arrow</li>"
    "<li>Right → Right arrow</li>"
    "<li>Down → Down arrow</li>"
    "<li>Left → Left arrow</li>"
    "</ul>"
    "<h4>Configuration Options</h4>"
    "<p><strong>Grid Dimensions:</strong> Customize grid height and width independently (e.g., 4×4, 8×8, 6×10). Default: 8×8.</p>"
    "<p><strong>Start Position:</strong> Choose where the agent begins. Default: (0, 0) top-left corner.</p>"
    "<p><strong>Goal Position:</strong> Select the target tile from available non-hole positions. Default: bottom-right for standard grids.</p>"
    "<p><strong>Hole Count:</strong> Adjust the number of holes in the grid. Default: 4 for 4×4, 10 for 8×8.</p>"
    "<p><strong>Random Holes:</strong> Toggle between official Gymnasium hole layouts (OFF) and randomly generated placements (ON). Default: OFF.</p>"
    "<p><strong>is_slippery:</strong> When True, movement is stochastic (agent may slip to perpendicular directions); when False, movement is deterministic. Default: False (deterministic).</p>"
    "<p><strong>success_rate:</strong> Probability of moving in the intended direction when <code>is_slippery=True</code>. Default: 1/3.</p>"
    "<p><strong>reward_schedule:</strong> Tuple of (goal_reward, hole_reward, step_reward). Default: (1, 0, 0).</p>"
    "<p><strong>Note:</strong> With Random Holes OFF, the environment uses the official Gymnasium maps with fixed hole positions for 4×4 and 8×8 grids. With Random Holes ON, holes are placed randomly based on the hole count.</p>"
    "<p>See the docs: <a href=\"https://gymnasium.farama.org/environments/toy_text/frozen_lake/\">FrozenLake (Gymnasium)</a></p>"
)


CLIFF_HTML = (
    "<h3>CliffWalking-v0</h3>"
    "<p>Navigate from start to goal along a cliff; stepping off the cliff is heavily penalized.</p>"
    "<h4>Starting state</h4>"
    "<p>Player starts in state 36 (row 3, column 0) by default.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>-1 per step</li>"
    "<li>-100 for stepping into the cliff squares</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: reaching the goal state (state 47)</li>"
    "</ul>"
    "<h4>Keyboard (human controls)</h4>"
    "<ul>"
    "<li>Up → Up arrow</li>"
    "<li>Right → Right arrow</li>"
    "<li>Down → Down arrow</li>"
    "<li>Left → Left arrow</li>"
    "</ul>"
    "<p>See the docs: <a href=\"https://gymnasium.farama.org/environments/toy_text/cliff_walking/\">CliffWalking (Gymnasium)</a></p>"
)


BLACKJACK_HTML = (
    "<h3>Blackjack-v1</h3>"
    "<p>A card game where the goal is to beat the dealer by obtaining cards that sum closer to 21 (without going over) than the dealer's cards.</p>"
    "<h4>Card Values</h4>"
    "<ul>"
    "<li>Face cards (Jack, Queen, King) → 10 points</li>"
    "<li>Aces → 11 (usable ace) or 1 point</li>"
    "<li>Numerical cards (2-10) → face value</li>"
    "</ul>"
    "<h4>Starting state</h4>"
    "<p>The game starts with the dealer having one face-up and one face-down card, while the player has two face-up cards. Player's sum ranges from 4-21, dealer's showing card is 1-10 (Ace-10).</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Win game → +1</li>"
    "<li>Lose game → -1</li>"
    "<li>Draw game → 0</li>"
    "<li>Win with natural blackjack → +1.5 (if natural=True) or +1 (if natural=False)</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: player hits and exceeds 21 (bust), or player sticks</li>"
    "</ul>"
    "<h4>Info returned</h4>"
    "<p><code>step()</code> and <code>reset()</code> return an <code>info</code> dict (currently empty).</p>"
    "<h4>Keyboard (human controls)</h4>"
    "<p>Map the Blackjack action space to keys for human play:</p>"
    "<ul>"
    "<li>Stick (0) → 1 or Q</li>"
    "<li>Hit (1) → 2 or E</li>"
    "</ul>"
    "<h4>Arguments / Config</h4>"
    "<p><code>natural</code>: If True, give +1.5 reward for starting with a natural blackjack (ace + 10-value card, sum is 21). Default: False.</p>"
    "<p><code>sab</code>: If True, follow exact rules from Sutton and Barto's book. When sab=True, natural is ignored. If player achieves natural and dealer does not, player wins (+1). If both get natural, it's a draw (0). Default: False.</p>"
    "<p>See the docs: <a href=\"https://gymnasium.farama.org/environments/toy_text/blackjack/\">Blackjack (Gymnasium)</a></p>"
)

__all__ = [
    "TAXI_HTML",
    "FROZEN_HTML",
    "FROZEN_V2_HTML",
    "CLIFF_HTML",
    "BLACKJACK_HTML",
]
