"""Utilities for validating JaxMARL worker configurations via dry-run."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Tuple


def _merge_output(stdout: Any, stderr: Any) -> str:
    """Merge stdout and stderr into a single string."""
    parts: list[str] = []
    for chunk in (stdout, stderr):
        if not chunk:
            continue
        if isinstance(chunk, bytes):
            parts.append(chunk.decode("utf-8", errors="replace"))
        else:
            parts.append(str(chunk))
    return "".join(parts)


def run_jaxmarl_dry_run(
    config_payload: Dict[str, Any],
    *,
    timeout_seconds: int = 60,
) -> Tuple[bool, str]:
    """Execute ``jaxmarl_worker.cli`` in ``--dry-run`` mode to validate a payload.

    Spawns a subprocess to validate the JaxMARL worker configuration without
    launching training. Validates: JSON syntax, required fields (run_id, algo,
    env_family, variant), enum membership (algo in {mappo, ippo}, env_family in
    {soccer, af, bb}, variant in known set), numeric ranges, and that the
    jaxmarl_worker package imports cleanly.

    Args:
        config_payload: Trainer configuration dictionary generated by the
            JaxMARL form. May be either the flat worker config or the nested
            GUI format (with ``metadata.worker.config``).
        timeout_seconds: Maximum time to wait for the subprocess.

    Returns:
        Tuple of (success, combined_output). ``success`` is True when the
        subprocess exits 0. ``combined_output`` is stdout+stderr, useful for
        appending to the Notes field or showing in a dialog.

    Example:
        >>> config = {
        ...     "run_id": "test",
        ...     "algo": "mappo",
        ...     "env_family": "soccer",
        ...     "variant": "G-1v0",
        ... }
        >>> success, output = run_jaxmarl_dry_run(config)
        >>> if success:
        ...     print("Configuration valid!")
        ... else:
        ...     print(f"Validation failed: {output}")
    """
    with tempfile.TemporaryDirectory(prefix="jaxmarl-dry-run-") as tmp_dir:
        config_path = Path(tmp_dir) / "config.json"
        config_path.write_text(json.dumps(config_payload, indent=2), encoding="utf-8")

        command = [
            sys.executable,
            "-m",
            "jaxmarl_worker.cli",
            "--config",
            str(config_path),
            "--dry-run",
            "--emit-summary",
        ]

        env = os.environ.copy()
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout_seconds,
                env=env,
            )
        except subprocess.TimeoutExpired as exc:  # pragma: no cover
            output = _merge_output(exc.stdout, exc.stderr)
            return False, output or "JaxMARL dry-run timed out"

    output = _merge_output(result.stdout, result.stderr)
    success = result.returncode == 0
    if not success and not output:
        output = "JaxMARL dry-run failed without output."
    return success, output


__all__ = ["run_jaxmarl_dry_run"]
